version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "4567:4567"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
