services:
  - type: web
    name: backend
    plan: free
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend

  - type: web
    name: frontend
    plan: free
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    # staticPublishPath: ./build
